# Generated by Django 4.2.5 on 2023-09-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_task_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='etiquetas',
            field=models.ManyToManyField(related_name='tareas', to='taskmanager.tag'),
        ),
    ]
