# Generated by Django 4.2.5 on 2023-09-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_alter_task_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='prioridad',
            field=models.BooleanField(default=False),
        ),
    ]
